// <auto-generated />
using CarsProject.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarsProject.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20240509153835_InitialCreating")]
    partial class InitialCreating
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarsProject.Domain.BrandVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameBrand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BrandVehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameBrand = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            NameBrand = "Mazda"
                        },
                        new
                        {
                            Id = 3,
                            NameBrand = "JAC"
                        },
                        new
                        {
                            Id = 4,
                            NameBrand = "Mitsubishi"
                        },
                        new
                        {
                            Id = 5,
                            NameBrand = "Datsun"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
